//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NobelMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cidade()
        {
            this.CidadeAntigo = new HashSet<Cidade>();
            this.Filiacao = new HashSet<Filiacao>();
            this.LaureadoIndividuoNascimento = new HashSet<LaureadoIndividuo>();
            this.LaureadoIndividuoMorte = new HashSet<LaureadoIndividuo>();
        }
    
        public int CidadeId { get; set; }
        public string Nome { get; set; }
        public int PaisId { get; set; }
        public Nullable<int> CidadeAtualId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cidade> CidadeAntigo { get; set; }
        public virtual Cidade CidadeAtual { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filiacao> Filiacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaureadoIndividuo> LaureadoIndividuoNascimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaureadoIndividuo> LaureadoIndividuoMorte { get; set; }
    }
}
