//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NobelApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaureadoOrganizacao
    {
        public int LaureadoId { get; set; }
        public string Nome { get; set; }
    
        public virtual Laureado Laureado { get; set; }
    }
}
