//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NobelApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaureadoIndividuo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaureadoIndividuo()
        {
            this.Filiacao = new HashSet<Filiacao>();
        }
    
        public int LaureadoId { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public Nullable<System.DateTime> DataMorte { get; set; }
        public int CidadeNascimentoId { get; set; }
        public Nullable<int> CidadeMorteId { get; set; }
        public string Sexo { get; set; }
    
        public virtual Cidade CidadeNascimento { get; set; }
        public virtual Cidade CidadeMorte { get; set; }
        public virtual Laureado Laureado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filiacao> Filiacao { get; set; }
    }
}
